### ISSUE TITLE
その他のファイルタイプへの対応

### ISSUE THREAD

**Issue by yamamoto-yuta** [ShotaroKataoka/richcat#16]
これで対応できそう
https://rich.readthedocs.io/en/latest/syntax.html

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
from_path?

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
拡張子判別の条件分岐で，elseをfrom_pathにしてみようかなと思ってます

**Comment by ShotaroKataoka** [comment]
なるほど
ipynbとかcsvの場合もいけるの？

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
↓みたいな実装をイメージしてます．
```
if filetype == 'csv':
   return <CSVファイルのrichテキストを出力する処理>
if filetype == 'ipynb'
   return <Jupyter notebookファイルのrichテキストを出力する処理>
...
else:
   return Syntaxfrom_path()
```

**Comment by ShotaroKataoka** [comment]
@yamamoto-yuta 
あ．なるほど！
それはかなりいいと思います

**Comment by yamamoto-yuta** [comment]
@ShotaroKataoka 
じゃあその方向で対応してみます！

**Comment by yamamoto-yuta** [comment]
↓で対応完了
https://github.com/ShotaroKataoka/richcat/tree/topic/v0.0.1/issue-016_adapt-other-filetypes
